export interface IProduct {
    id: number | null,
    name: string,
    date: string,
    ram: number,
    storage: number,
    AppName: string,
    AppAccount: string,
    listPrice: number,
    cardAmount: number,
    costToMe: number,
    dPrice: number,
    coupon: number,
    giftBalence: number,
    cardDiscount: number,
    cardHolder: string,
    deliveryDate: string,
    deliveryLoc: string,
    finalDelDate:string,
    distName: string
}