export interface IProduct {
    id: number | null,
    name: string,
    date: string,
    ram: number,
    storage: number,
    AppName: string,
    AppAccount: string,
    listPrice: number | null,
    cardAmount: number | null,
    costToMe: number | null,
    dPrice: number | null,
    coupon: number | null,
    giftBalence: number | null,
    cardDiscount: number | null,
    cardHolder: string,
    deliveryDate: string,
    deliveryLoc: string,
    finalDelDate:string,
    distName: string,
    status: string
}